root_path: static
write_files:
  - path: static/data/areas/1.json
    interval: 5
    data:
      - "{'1': '1'}"
      - "{'2': '2'}"
  - path: static/data/areas/3.json
    interval: 3
    data:
      - "{'3': '3'}"
      - "{'4': '4'}"
      - "{'5': '5'}"
      - "{'6': '6'}"
      - "{'7': '7'}"
      - "{'8': '8'}"
